# Site configuration
domain: "https://liutianhou.github.io"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://liutianhou.github.io" # the base hostname & protocol for your site
permalink: /:title/
avatar: 
about: 
favicon: 
basecss:
# Theme specific configuration
title: 一个小白
description: >
  你好，我是 一个小白。这是我的个人博客，用来记录技术与生活随笔。
  欢迎交流与指正。

# Contact and social media links
twitter_username: 
github_username: 一个小白
facebook_username: 
instagram_username: 
linkedin_username: 

exclude: ['node_modules', 'gulpfile.js', 'package.json']

kramdown:
  input: GFM

# If U enable the comment, edit disqus or duoshuo account of "/_layouts/post.html"
# before deploy your webpage
enable_comment: false

gems: ['jekyll-paginate']
# Pagination
paginate: 5
paginate_path: /archive/page:num
